version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "postcodeapistack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2647npur4ct5"
s3_prefix = "postcodeapistack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
