AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for postcodesvc

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    # Auth:
    #   DefaultAuthorizer: LambdaTokenAuthorizer
    #   Authorizers:
    #     LambdaTokenAuthorizer:
    #       FunctionArn: !GetAtt ApiAuthFunction.Arn
      
Resources:
  PostCodeSvcFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./src/PostCodeSvc/
      Handler: PostCodeSvc::PostCodeSvc.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: 
        Variables:
          PARAM1: VALUE
      Events:
        Lookup:
          Type: Api 
          Properties:
            Path: /lookup
            Method: get            
            RequestParameters:
              - method.request.querystring.postcode
        Autocomplete:
          Type: Api 
          Properties:
            Path: /autocomplete
            Method: get            
            RequestParameters:
              - method.request.querystring.postcode
  # ApiAuthFunction:
  #     Type: AWS::Serverless::Function 
  #     Properties:
  #       CodeUri: ./src/ApiAuth/
  #       Handler: ApiAuth::ApiAuth.Function::FunctionHandler
  #       Runtime: dotnetcore3.1
  #       Architectures:
  #         - x86_64
  #       MemorySize: 256

Outputs:
  PostCodeSvcApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lookup?postcode=NE30%201DP"
  PostCodeSvcFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PostCodeSvcFunction.Arn
  PostCodeSvcFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PostCodeSvcFunctionRole.Arn
