AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for postcodesvc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      
Resources:
  PostCodeSvcFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/PostCodeSvc/
      Handler: PostCodeSvc::PostCodeSvc.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Lookup:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lookup
            Method: get            
            RequestParameters:
              - method.request.querystring.postcode
        Autocomplete:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /autocomplete
            Method: get            
            RequestParameters:
              - method.request.querystring.postcode

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostCodeSvcApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lookup?postcode=NE30%201DP"
  PostCodeSvcFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PostCodeSvcFunction.Arn
  PostCodeSvcFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PostCodeSvcFunctionRole.Arn
